language: cpp
compiler: gcc
before_script:
 - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip -O /tmp/gtest-1.7.0.zip
 - unzip /tmp/gtest-1.7.0.zip
 - GTEST_PATH=$PWD/gtest-1.7.0
 - export GTEST_PATH
 - cd gtest-1.7.0 && ./configure && make && cd ..

script: ./configure --with-gtest=$PWD/gtest-1.7.0 && make && make check

